# TODO Add SSL
# Add monitor
# make addresses configuarable (which ones?)
version: '2.2'
services:
  #nginx
  nginx:
    image: nginx:latest
    container_name: nginx_container
    build: .
    depends_on:
      - es01
      - es02
      - es03
    #command:
      #- bin/bash
      #- -c
      #- apt update
      #- apt install apache2-utils -y
      #- htpasswd /etc/nginx/.htpasswd #{USER_NAME}
      #- cat /etc/nginx/.htpasswd
      #- echo "Above is your username and password"
      #- sleep 6
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/credentials:/etc/nginx/credentials
    networks:
        esnet:
          ipv4_address: 172.19.0.2
# es pods
  es01:
    image: elasticsearch:${ES_VERSION}
    container_name: elasticsearch1
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=${ALLOCATED_HEAP}
      - discovery.zen.ping.unicast.hosts=es02,es03
      - discovery.zen.minimum_master_nodes=2
    ports:
      - 127.0.0.1:9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: ${MEM_LIMIT}
    volumes:
      - ${DATA_LOCATION1}:/usr/share/elasticsearch/data
    networks:
        esnet:
          ipv4_address: 172.19.0.3

  es02:
    image: elasticsearch:${ES_VERSION}
    container_name: elasticsearch2
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=${ALLOCATED_HEAP}
      - discovery.zen.ping.unicast.hosts=es01,es03
      - discovery.zen.minimum_master_nodes=2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: ${MEM_LIMIT}
    volumes:
      - ${DATA_LOCATION2}:/usr/share/elasticsearch/data
    networks:
        esnet:
          ipv4_address: 172.19.0.4

  es03:
    image: elasticsearch:${ES_VERSION}
    container_name: elasticsearch3
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=${ALLOCATED_HEAP}
      - discovery.zen.ping.unicast.hosts=es01,es02
      - discovery.zen.minimum_master_nodes=2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: ${MEM_LIMIT}
    volumes:
      - ${DATA_LOCATION3}:/usr/share/elasticsearch/data
    networks:
        esnet:
          ipv4_address: 172.19.0.5
#kibana
  kb:
    image: kibana:4.1.11
    container_name: kibana
    build: .
    depends_on:
      - es01
      - es02
      - es03
    environment:
      - ELASTICSEARCH_URL=http://es01:9200
    ports:
       - 127.0.0.1:5601:5601
    networks:
        esnet:
          ipv4_address: 172.19.0.6
networks:
  esnet:
    ipam:
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1
volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
